name: Jekyll Themes
url: http://matt.harzewski.com
description: Insert tagline here

permalink: /themes/:title/

gems: [jekyll-paginate]


paginate: 20



exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile', 'vendor']

theme: jekyll-theme-minimal
